//TODO: add cars from backend
List<Map> cars = [
  {
    'carName': 'Skoda Rapid 2022',
    'carClass': 'Sport',
    'carPower': 200,
    'seater': '5',
    'type': 'Manual',
    'bags': '1-5',
    'carImage': 'assets/images/rapid.png',
    'carPrice': 2700,
    'isRotated': true,
    'carRating': '4.5',
  },
  {
    'carName': 'Volkswagen Polo 2020',
    'carClass': 'Sport',
    'carPower': 180,
    'seater': '4',
    'type': 'Manual',
    'bags': '1-4',
    'carImage': 'assets/images/poloGT.png',
    'carPrice': 2550,
    'isRotated': true,
    'carRating': '4.2',
  },
  {
    'carName': 'Hyundai i20 2021',
    'carClass': 'Economy',
    'carPower': 150,
    'seater': '5',
    'type': 'Manual',
    'bags': '1-3',
    'carImage': 'assets/images/i30-hyundai.png',
    'carPrice': 2100,
    'isRotated': false,
    'carRating': '5.0',
  },
  {
    'carName': 'Toyota Yaris 2019',
    'carClass': 'City',
    'carPower': 130,
    'seater': '5',
    'type': 'Automatic',
    'bags': '1-2',
    'carImage': 'assets/images/yaris-toyota.png',
    'carPrice': 1500,
    'isRotated': false,
    'carRating': '4.8',
  }
];
